name: cyclepathsg
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# ------------------- PACKAGES -------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5

  # Product Specific
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  provider: ^6.1.5
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  device_preview: ^1.3.1

  flutter_polyline_points: ^3.0.1
  cherry_toast: ^1.13.0 # for toast message
  font_awesome_flutter: ^10.9.1 # for icon
  cloud_firestore: ^6.0.3

# ------------------- PACKAGES END -------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  # ---------------- LOCAL ASSETS ---------------------- #
  assets:
     - assets/logos/
     - assets/fonts/
     - assets/icons/
     - assets/imgs/


# ---------------- LOCAL FONTS ---------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/StoryScript-Regular.ttf
